### ISSUE TITLE
Error running on clusters folder produced by isONclust

### ISSUE THREAD

**Issue by edgardomortiz** [ksahlin/isONcorrect#4]
Hello Kristoffer,

I tried running `run_isoncorrect` after running `isONclust`:
```
run_isconcorrect --t 1 --fastq_folder fastq_files --outfolder fastq_corrected
```
And the computer crashed, before that, I noticed all 24 cores were being used and also the entire 64GB of RAM.
So, I tried without the `--t` flag, and this error was produced (multiple times):
```
('/Users/pbiodiv/miniconda3/envs/isontools/bin', 'fastq_reduced/10.fastq', 'fastq_corrected/10', '10', {'set_w_dynamically': False, 'exact_instance_limit': 50, 'k': 9, 'w': 10, 'xmin': 14, 'xmax': 80, 'T': 0.1, 'max_seqs': 1000, 'use_racon': False})
('/Users/pbiodiv/miniconda3/envs/isontools/bin', 'fastq_reduced/11.fastq', 'fastq_corrected/11', '11', {'set_w_dynamically': False, 'exact_instance_limit': 50, 'k': 9, 'w': 10, 'xmin': 14, 'xmax': 80, 'T': 0.1, 'max_seqs': 1000, 'use_racon': False})
('/Users/pbiodiv/miniconda3/envs/isontools/bin', 'fastq_reduced/12.fastq', 'fastq_corrected/12', '12', {'set_w_dynamically': False, 'exact_instance_limit': 50, 'k': 9, 'w': 10, 'xmin': 14, 'xmax': 80, 'T': 0.1, 'max_seqs': 1000, 'use_racon': False})
('/Users/pbiodiv/miniconda3/envs/isontools/bin', 'fastq_reduced/13.fastq', 'fastq_corrected/13', '13', {'set_w_dynamically': False, 'exact_instance_limit': 50, 'k': 9, 'w': 10, 'xmin': 14, 'xmax': 80, 'T': 0.1, 'max_seqs': 1000, 'use_racon': False})
('/Users/pbiodiv/miniconda3/envs/isontools/bin', 'fastq_reduced/14.fastq', 'fastq_corrected/14', '14', {'set_w_dynamically': False, 'exact_instance_limit': 50, 'k': 9, 'w': 10, 'xmin': 14, 'xmax': 80, 'T': 0.1, 'max_seqs': 1000, 'use_racon': False})
('/Users/pbiodiv/miniconda3/envs/isontools/bin', 'fastq_reduced/15.fastq', 'fastq_corrected/15', '15', {'set_w_dynamically': False, 'exact_instance_limit': 50, 'k': 9, 'w': 10, 'xmin': 14, 'xmax': 80, 'T': 0.1, 'max_seqs': 1000, 'use_racon': False})
<multiprocessing.context.SpawnContext object at 0x105226650>
Environment set: <multiprocessing.context.SpawnContext object at 0x105226650>
Using 8 cores.
Running isoncorrect batch_id:10... Running isoncorrect batch_id:11... Running isoncorrect batch_id:12... Running isoncorrect batch_id:13... Running isoncorrect batch_id:14... Running isoncorrect batch_id:15... multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/pbiodiv/miniconda3/envs/isontools/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/pbiodiv/miniconda3/envs/isontools/bin/run_isoncorrect", line 99, in isoncorrect
    "--T",  str(isoncorrect_algorithm_params["T"]) ], stderr=error_file, stdout=isoncorrect_out_file)
  File "/Users/pbiodiv/miniconda3/envs/isontools/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/time', '/Users/pbiodiv/miniconda3/envs/isontools/bin/isONcorrect', '--fastq', 'fastq_reduced/15.fastq', '--outfolder', 'fastq_corrected/15', '--exact_instance_limit', '50', '--max_seqs', '1000', '--k', '9', '--w', '10', '--xmin', '14', '--xmax', '80', '--T', '0.1']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pbiodiv/miniconda3/envs/isontools/bin/run_isoncorrect", line 335, in <module>
    main(args)
  File "/Users/pbiodiv/miniconda3/envs/isontools/bin/run_isoncorrect", line 275, in main
    for x in pool.imap_unordered(isoncorrect, instances):
  File "/Users/pbiodiv/miniconda3/envs/isontools/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
subprocess.CalledProcessError: Command '['/usr/bin/time', '/Users/pbiodiv/miniconda3/envs/isontools/bin/isONcorrect', '--fastq', 'fastq_reduced/15.fastq', '--outfolder', 'fastq_corrected/15', '--exact_instance_limit', '50', '--max_seqs', '1000', '--k', '9', '--w', '10', '--xmin', '14', '--xmax', '80', '--T', '0.1']' returned non-zero exit status 1.
```
I have `run_isoncorrect 0.0.6`, the same error occurs after adding `--T 0.05 --use_racon`. I also attach a subsample of the clusters. Any help is appreciated.

Edgardo

[clusters.tar.gz](https://github.com/ksahlin/isONcorrect/files/4776502/clusters.tar.gz)

**Comment by ksahlin** [comment]
Hi Edgardo,

Thanks for the report. Is there any chance you could share the file 'fastq_reduced/15.fastq' here or through email (ksahlin@kth.se)? That way I can fix the eventual bug.

Best,
K

**Comment by edgardomortiz** [comment]
I just checked, it should be inside https://github.com/ksahlin/isONcorrect/files/4776502/clusters.tar.gz

**Comment by ksahlin** [comment]
It worked for me when running
```
./isONcorrect --fastq ~/Downloads/fastq_reduced/15.fastq \
--outfolder ~/Downloads/fastq_reduced/15_out  \
--exact_instance_limit 50 --max_seqs 1000 --k 9 --w 10 --xmin 14 --xmax 80 --T 0.1
```
I got
```
xmin set to 18
Total cluster of 4 reads.
ARGUMENT SETTINGS:
fastq: /Users/kxs624/Downloads/fastq_reduced/15.fastq
k: 9
w: 10
xmin: 18
xmax: 80
T: 0.1
exact: True
disable_numpy: False
max_seqs_to_spoa: 200
max_seqs: 1000
use_racon: False
exact_instance_limit: 50
set_w_dynamically: False
verbose: False
compression: False
outfolder: /Users/kxs624/Downloads/fastq_reduced/15_out

Temporary workdirektory: /var/folders/6n/tw49pymn3jq4khf0jsv97vmr0000gp/T/tmpa7yx34c2
correcting 4 reads in a batch
353563 MINIMIZER COMBINATIONS GENERATED
Average abundance for non-unique minimizer-combs: 2.0797838405824294
Number of singleton minimizer combinations filtered out: 298143

Done with batch_id: 0
Took 3.3091588020324707 seconds.
4
removing temporary workdir
```

Could you try  running this comment instead (i.e. running isONclust on one instance, not using the `run_isoncorrect` script ). This way we can see  the details of the error.

Best,
K

**Comment by edgardomortiz** [comment]
Cool, I will run `isONcorrect` with the parameters you showed. Or maybe 15 is OK, and some other file in the 5 fastqs I uploaded caused the error? I ran `run_isoncocrrect` on the entire folder.

Thanks!

**Comment by ksahlin** [comment]
I checked all clusters 10-15 and they all worked for me.

**Comment by edgardomortiz** [comment]
When I ran `isONcorrect` with a single file it became clear I was missing `spoa`!
Now I will use these commands to install it:
```
conda create -n isontools python=3 pip "edlib>=1.1.2" python-edlib "pysam>=0.11" "networkx<=2.3" "parasail-python>=1.1.10" spoa
conda activate isontools
pip install IsoCon isONclust isONcorrect
```
Now everything runs normal, sorry!
